apiVersion: v1
kind: Service

metadata:
  name: product-service

spec:
  selector:
    app: product

  ports:
    - protocol: TCP
      port: {{ .Values.product.port }}
      targetPort: {{ .Values.product.port }}

  type: ClusterIP