apiVersion: v1
kind: Secret

metadata:
  name: microservice-secret

type: Opaque

stringData:
  MONGO_URI: mongodb+srv://Firdous:Zuni2058Mongo@cluster0.hwth0kg.mongodb.net/?appName=Cluster0
  JWT_SECRET: mySecretKey
