apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
        - name: auth
          image: firdousalam2058/auth-service:v6
          imagePullPolicy: Always

          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: microservice-secret
                  key: MONGO_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: microservice-secret
                  key: JWT_SECRET

            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: microservice-config
                  key: NODE_ENV