apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: product

  template:
    metadata:
      labels:
        app: product

    spec:
      containers:
        - name: product
          image: firdousalam2058/product-service:v6
          imagePullPolicy: Always

          ports:
            - containerPort: 3002

          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: microservice-secret
                  key: MONGO_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: microservice-secret
                  key: JWT_SECRET

            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: microservice-config
                  key: NODE_ENV